---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  data_bags_path: data_bags
  require_chef_omnibus: 11.18.12-1

platforms:
  - name: centos-6.5

suites:
  - name: 0.17.2
    driver:
      network:
        - ["forwarded_port", {guest: 4567, host: 4567}]
    run_list:
      - recipe[uchiwa-sensu::server]
      - recipe[uchiwa-sensu::client]
    attributes:
      sensu:
        version: "0.17.2-1"
        use_embedded_ruby: true
        yum_repo_url: "http://repos.sensuapp.org"
        rabbitmq:
          host: "127.0.0.1"
        api:
          host: "0.0.0.0"
          user: "admin"
          password: "secret"
      yum:
        erlang_solutions:
          baseurl: "http://packages.erlang-solutions.com/rpm/centos/6/$basearch"
  - name: 0.21.0
    driver:
      network:
        - ["forwarded_port", {guest: 4567, host: 4568}]
        - ["forwarded_port", {guest: 6379, host: 6379}]
    run_list:
      - recipe[uchiwa-sensu::server]
      - recipe[uchiwa-sensu::client]
    attributes:
      sensu:
        version: "0.21.0-2"
        use_embedded_ruby: true
        rabbitmq:
          host: "127.0.0.1"
        api:
          host: "0.0.0.0"
          user: "admin"
          password: "secret"
      yum:
        erlang_solutions:
          baseurl: "http://packages.erlang-solutions.com/rpm/centos/6/$basearch"
  - name: 0.21.0-bis
    driver:
      network:
        - ["forwarded_port", {guest: 4567, host: 4569}]
    run_list:
      - recipe[sensu::default]
      - recipe[sensu::api_service]
    attributes:
      sensu:
        version: "0.21.0-2"
        use_embedded_ruby: true
        yum_repo_url: "http://repositories.sensuapp.org"
        redis:
          host: "10.73.0.10"
        api:
          host: "0.0.0.0"
          user: "admin"
          password: "secret"
      yum:
        erlang_solutions:
          baseurl: "http://packages.erlang-solutions.com/rpm/centos/6/$basearch"
  - name: enterprise
    driver:
      customize:
        memory: 2560
      network:
        - ["forwarded_port", {guest: 4567, host: 4570}]
    run_list:
      - recipe[uchiwa-sensu::enterprise]
      - recipe[uchiwa-sensu::client]
    attributes:
      sensu:
        enterprise:
          version: "1.7.2-1"
        rabbitmq:
          host: "127.0.0.1"
        api:
          host: "0.0.0.0"
          user: "admin"
          password: "secret"
      yum:
        erlang_solutions:
          baseurl: "http://packages.erlang-solutions.com/rpm/centos/6/$basearch"
